### ISSUE TITLE
2019 Roadmap

### ISSUE THREAD

**Issue by CodyJasonBennett** [armtg/ARMTG-Website#1]
### Phase 1
- [x] Recognition of up to 60 unique trackers (Corresponding with cards #1-#60)
- [x] Card image fetching from Decklist (perhaps using the Scryfall API)
### Phase 2
- [ ] Game interface and controls
- [ ] Game-related info (Cards in hand, library)
### Phase 3
- [ ] GUI for sideboarding (Drag and drop between main/side deck from submitted decklist)
- [ ] More advanced metrics like cards in graveyard/exile
### Phase 4
- [ ] GUI for Deckbuilding (stuff like card image preview, similar to that of untap.xyz)
- [ ] GUI for Saving multiple decklists
### Phase 5
- [ ] Interactive Game engine (The stack, and phases)
- [ ] GUI for timers (for each round, and for sideboarding)
